version: "3"
services:
  nginx:
    image: nginx:1.13.7-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php    
    volumes:
      - ../app/:/var/www/html/:rw
      - $PWD/config/nginx:/etc/nginx/conf.d:ro
      - ./data/logs/nginx/:/var/logs/nginx:rw
    restart: always
  php:
    image: kimlyfly/php-7.2-fpm
    container_name: php
    volumes:
      - ../app:/var/www/html/:rw
      - $PWD/config/php/conf.d:/usr/local/etc/php/conf.d:ro
      # php和mysql通信
      - ./data/mysql/run/mysqld:/var/run/mysqld:rw
    links:
      - mysql
      - redis
    restart: always
  mysql:
    image: mysql:5.7.20
    container_name: mysql
    # 配置环境变量
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      # mysql 配置文件
      - $PWD/config/mysql/conf.d:/etc/mysql/conf.d:ro
      # 下面的目录配置文件会覆盖上面的
      - $PWD/config/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d:ro
      # mysql 数据库
      - ./data/mysql/data:/var/lib/mysql:rw
      # mysql 日志
      - ./data/logs/mysql:/var/logs/mysql:rw
      # php和mysql通信
      - ./data/mysql/run/mysqld:/var/run/mysqld:rw
    restart: always
  redis:
    image: redis:4.0.5-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      # redis 配置文件
      - $PWD/config/redis:/etc/redis:ro
      # redis 持久化数据存储
      - ./data/redis:/app/redis:rw
    # 以配置文件启动 redis
    command: redis-server /etc/redis/redis.conf
    restart: always
